version:"3"

services:
  wordpress:
    image:wordpress
    ports:
      - 80:80
    enviroment:
      WORDPRESS_DB_HOST:mysql
      WORDPRESS_DB_NAME:wp
      WORDPRESS_DB_USER:wp
      WORDPRESS_DB_PASSWORD:wp_pass
  mysql:
    image:mysql
    enviroment:
      MYSQL_USER:wp
      MYSQL_PASSWORD:wp_pass
      MYSQL_ROOT_PASSWORD:toor
  
  phpmyadmin:
    image:phpmyadmin
    ports:
      - 8080:80
    enviroment:
      PMA_HOST:mysql